server:
  port: 8080
  
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
        
feign:
  clients:
    product:
      url: ${PRODUCT_BASE_URL:https://dummyjson.com}