spring:
  config:
    activate:
      on-profile: dev
  
logging:
    level:
      root: DEBUG
      com:
        exemplo: TRACE
  
feign:
  clients:
    product:
      url: ${PRODUCT_BASE_URL:https://dummyjson.com}