spring:
  config:
    activate:
      on-profile: prod
  
logging:
    level:
      root: WARN
      com:
        exemplo: ERROR
        
feign:
  clients:
    product:
      url: ${PRODUCT_BASE_URL:https://dummyjson.com}